project_id = "raoqwwwkonogwlqkucuz"

[functions.groq-chat]
verify_jwt = false

[functions.lighthouse-upload]
verify_jwt = false

[functions.mint-nft]
verify_jwt = false

[functions.create-listing]
verify_jwt = false

[functions.duplicate-project]
verify_jwt = false
